name: goasbar
description: Go Asbar is an Air Bnb look a like for a Saoudi Startup

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.4

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  styled_widget: ^0.4.1
  flutter_hooks: ^0.20.5
  pinput: ^5.0.0
  string_validator: ^1.1.0
  animations: ^2.0.7
  carousel_slider: ^5.0.0
  calendar_date_picker2: ^1.0.2
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.7
  motion_toast: ^2.6.5
  dio: ^5.0.0
  flutter_rating_bar: ^4.0.1
  share_plus: ^10.1.2

  # Media Service
  image_picker: ^1.1.1

  # Architecture
  stacked: ^3.0.1
  stacked_services: ^1.5.0

  # Navigation
  auto_route: ^9.2.2

  # Injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # chat firebase
  cloud_firestore: ^5.4.5
  firebase_core: ^3.7.0

  # firebase auth
  firebase_auth: ^5.3.2

  # connectivity
  connectivity_plus: ^6.0.3

  # google maps
  google_maps_flutter: ^2.2.5
  geocoding: ^3.0.0
  webview_flutter: ^4.4.1
  mask_text_input_formatter: ^2.5.0
  stacked_core: ^1.2.4
  map_launcher: ^3.5.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.3.2
  injectable_generator: ^2.1.3
  stacked_generator: ^1.6.0

  # configs
  flutter_application_id: ^2.0.0-dev

flutter_application_id:
  android:
    id: "com.goasbar.goAsbar"
    name: "Go Asbar"
  ios:
    id: "com.goasbar.goAsbarApp"
    name: "Go Asbar"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/translations/
    - assets/icons/
    - assets/icons/navbar/
    - assets/icons/categories/
    - assets/icons/checkout/
    - assets/icons/settings/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
